[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "mbr.json"

# [target.i386-unknown-none-code16]
# rustflags = ["-C", "link-arg=-Tlinker.ld"]

[profile.release]
opt-level = "s"