[package]
name = "loader2"
version.workspace = true
edition.workspace = true

[dependencies]
os_in_rust_common = { workspace = true }
volatile = { workspace = true }

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
