[package]
name = "os_in_rust_common"
version.workspace = true
edition.workspace = true

[dependencies]
volatile = "0.2.6"
spin = "0.9.8"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.release]
opt-level = "s"